{% set version = "4.4_20160413" %}
{% set flat_version=version.replace(".", "") %}

package:
  name: tbb
  version: {{ version }}

source:
  fn: tbb{{ flat_version }}oss_src.tgz
  url: https://www.threadingbuildingblocks.org/sites/default/files/software_releases/source/tbb{{ flat_version }}oss_src.tgz
  sha1: d4cee5e4ca75cab5181834877738619c56afeb71

build:
  number: 1
  features:
    - vc9    # [win and py27]
    - vc10   # [win and py34]
    - vc14   # [win and py35]

requirements:
  build:
    - python  # [win]
    - cmake   # [win]

test:
  requires:
    - python 2.7.*  # [win and py27]
    - python 3.4.*  # [win and py34]
    - python 3.5.*  # [win and py35]

  commands:
    - test -f ${PREFIX}/include/tbb/tbb.h  # [unix]
    - test -f ${PREFIX}/lib/libtbb.so  # [linux]
    - test -f ${PREFIX}/lib/libtbb.dylib  # [osx]

about:
  home: http://www.threadingbuildingblocks.org
  license: GPL v2 (with runtime exception)
  summary: High level abstract threading library

extra:
  recipe-maintainers:
    - jschueller
