{% set version = "2018_20170726" %}

package:
  name: tbb
  version: {{ version }}

source:
  fn: tbb{{ version }}oss_src.tgz
  url: https://github.com/01org/tbb/archive/2018.tar.gz
  sha256: 94f643f1edfaccb57d64b503c7c96f00dec64e8635c054bbaa33855d72c5822d

build:
  number: 1
  features:
    - vc14  # [win and py>=35]
  skip: true  # [win and py36]

requirements:
  build:
    - toolchain
    - python  # [win]
    - cmake  # [win]

test:
  requires:
    - python {{ os.environ.get('PY_VER', '') + '*' }}  # [win]

  commands:
    - test -f ${PREFIX}/include/tbb/tbb.h  # [unix]
    - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libtbb${SHLIB_EXT}']"  # [unix]
    - python -c "import ctypes; ctypes.cdll[r'%PREFIX%\Library\bin\tbb.dll']"  # [win]
    - if not exist %PREFIX%\\Library\\include\\tbb\\tbb.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\tbb.lib exit 1  # [win]

about:
  home: http://www.threadingbuildingblocks.org
  license: Apache 2.0
  license_file: LICENSE
  summary: High level abstract threading library

extra:
  recipe-maintainers:
    - jschueller
