{% set version = "2021.4.0" %}

{% set vmajor = version.split('.')[0]|int %}
{% set vminor = version.split('.')[1]|int %}
{% set vpatch = version.split('.')[2]|int %}
{% set vbinary = vmajor - 2009 %}

{% set vtag = "v%d.%d.%d" % (vmajor, vminor, vpatch) %}

# Official patch version for the first release of 2021 is 1,
# but internal patch version is 0, handle it for interface version.
{% set vinterface = "%d" % (vbinary * 1000 + vminor * 10 + (vpatch if vmajor != 2021 or vminor != 1 else 0)) %}

# Libraries on Windows are expected to be installed into LIBRARY_PREFIX.
# tbb4py files should be installed into PREFIX.
# See https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html.
# On non-Windows CMAKE_ARGS already contains CMAKE_INSTALL_PREFIX.
{% set cmake_args = "$CMAKE_ARGS" %}  # [not win]
{% set cmake_args = "-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX%" %}  # [win]
{% set cmake_tbb4py_args = "$CMAKE_ARGS" %}  # [not win]
{% set cmake_tbb4py_args = "-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%PREFIX%" %}   # [win]

# Use specific test list agreed with TBB team to cover core functionality on high level.
# Execution of all tests is too heavy task for packaging CI.
{% set tests = "test_parallel_for test_tbb_header conformance_version test_malloc_compliance test_flow_graph test_arena_constraints" %}
{% set ctest_regex = "^(%s)$" % (tests.replace(' ', '|')) %}

{% set tbb4py_build_dir = "build_$PKG_HASH" %}  # [not win]
{% set tbb4py_build_dir = "build_%PKG_HASH%" %}  # [win]

package:
  name: tbb
  version: {{ version }}

source:
  fn: {{ vtag }}.tar.gz
  url: https://github.com/oneapi-src/oneTBB/archive/{{ vtag }}.tar.gz
  sha256: 021796c7845e155e616f5ecda16daa606ebb4c6f90b996e5c08aebab7a8d3de3

build:
  number: 1

requirements:
  build:
    - ninja
    - cmake
    - libhwloc
    - pkg-config

outputs:
  - name: hwloc-detection-debug
    build:
      script:
        - dir %CONDA_PREFIX%\Library\lib\  # [win]
        - ls ${CONDA_PREFIX}/lib  # [not win]
        - cmake -G Ninja .

about:
  home: https://github.com/oneapi-src/oneTBB
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - third-party-programs.txt
  summary: High level abstract threading library
  dev_url: https://github.com/oneapi-src/oneTBB
  doc_url: https://software.intel.com/en-us/oneapi-tbb-documentation

extra:
  recipe-maintainers:
    - anton-malakhov
    - jschueller
    - AlexVeprev
