{% set version = "2018.0.5" %}

{% set year = version.split('.')[0]|int %}
{% set update = version.split('.')[2]|int %}
{% if update == 0 %}
{%   set vtag = "%d" % year %}
{% else %}
{%   set vtag = "%d_U%d" % (year, update) %}
{% endif %}
{% set vinterface = (year-2008)*1000 + update %}  # just guess, does not fit the previous versions before 2018

{% set build = 'python build/build.py --make-tool=mingw32-make --build-prefix=vc%VS_MAJOR%' %}  # [win]
{% set build = 'python build/build.py --build-args="stdver=c++11"' %}                           # [unix]

package:
  name: tbb
  version: {{ version }}

source:
  fn: tbb{{ vtag }}_oss_src.tgz
  url: https://github.com/01org/tbb/archive/{{ vtag }}.tar.gz
  sha256: c4c2896af527392496c5e01ef8579058a71b6eebbd695924cd138841c13f07be

build:
  number: 0
  script_env:
    - OS    # [win]

requirements:
  build:
    - python *
    - {{ compiler('cxx') }}
    - m2w64-make                                         # [win]

test:
  requires:
    - python *               # any python version is ok for sake of testing of shared libraries
  commands:
    - python -c "import ctypes; assert {{ vinterface }} == ctypes.cdll[r'libtbb.so.2']       ['TBB_runtime_interface_version']()"  # [linux]
    - python -c "import ctypes; assert {{ vinterface }} == ctypes.cdll[r'libtbb${SHLIB_EXT}']['TBB_runtime_interface_version']()"  # [unix and not linux]
    - python -c "import ctypes; assert {{ vinterface }} == ctypes.cdll[r'tbb.dll']           ['TBB_runtime_interface_version']()"  # [win]

outputs:
  - name: tbb
    build:
      script: {{ build }} --install-libs

  - name: tbb-devel
    build:
      script: {{ build }} --no-rebuild --install-devel --install-docs
    requirements:
      build:
        - python *
        - {{ compiler('cxx') }}
        - m2w64-make                                     # [win]
      run:
        - {{ pin_subpackage('tbb', exact=True) }}        # development package is for specific version of tbb
    test:
      commands:
        - if not exist %PREFIX%\Library\include\tbb\tbb.h exit 1  # [win]
        - if not exist %PREFIX%\Library\lib\tbb.lib exit 1        # [win]
        - test -f ${PREFIX}/include/tbb/tbb.h                     # [unix]

  - name: tbb4py
    build:
      script: {{ build }} --no-rebuild --install-python
      entry_points:
        - python-tbb = tbb:_main
    requirements:
      build:
        - {{ compiler('cxx') }}
        - m2w64-make                                     # [win]
        - swig
      host:
        - python
        - {{ pin_subpackage('tbb-devel', exact=True) }}
      run:
        - tbb >={{ version }}                            # while python module works with any compatible tbb...
        - python
    test:
      requires:
        - python
        - {{ pin_subpackage('tbb', exact=True) }}        # we want to test with this specific tbb package
      imports:
        - tbb
        - TBB
      commands:
        - python-tbb -h
        - python -m TBB -h
        - python -m tbb -h
        - python -m tbb test
    about:
      summary: TBB module for Python
      license: Apache 2.0
      dev_url: https://github.com/01org/tbb

about:
  home: http://www.threadingbuildingblocks.org
  license: Apache 2.0
  license_file: LICENSE
  summary: High level abstract threading library
  dev_url: https://github.com/01org/tbb
  doc_url: https://software.intel.com/en-us/node/506039

extra:
  recipe-maintainers:
    - jschueller
    - anton-malakhov
